Refactor Auth so that the interceptor is in its own class.
tair/mb4-service pull request #61
Opened 2023-05-04 12:50 UTC by kenzley

Also remove the "Bearer" symbol in the string since it's no longer a part of the Header.

2023-05-04 19:18 UTC, ChenXingguo requested changes
Can we keep a consistent naming pattern? Please rename the handler to use "-" to connect instead of "_"

2023-05-05 03:43 UTC, kenzley commented
> Member
Done

2023-05-05 03:43 UTC, kenzley reviewed
Done

2023-05-05 19:45 UTC, ChenXingguo approved these changes

2023-05-05 19:46 UTC, merged